import { buildNode, BuilderCB } from './builder';
import { renderNode } from './render';

export function render(containerElement: HTMLElement, rootBuilder: BuilderCB) {
  const rootNode = buildNode(null, rootBuilder);
  const rootElement = renderNode(rootNode);
  containerElement.innerHTML = '';
  containerElement.appendChild(rootElement);
  /*
  The drawback with this method (line 7 & 8) is that there will always be two "root" elements in the dom.
  The first one is the "containerElement" provided by the user.
  The second one is the "rootElement" generated by "renderNode".

  On the other hand, since the "rootElement" only belongs to paramus-render we can do what we want with it.
  This is really helpful since the current implementation doesn't do any delta calculations when updating the dom.
  So since we dont calculate any delta and we own the rootElement, 
    we can simply remove it from the dom and generate a new one on each render.
  */
}